#!/usr/bin/env bash
# Generate lightweight API docs from the Rust Tauri command surface.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$REPO_ROOT"

OUT_DIR="docs/api"
OUT_FILE="${OUT_DIR}/tauri-commands.md"
mkdir -p "$OUT_DIR"

echo "Generating ${OUT_FILE} ..."

{
  echo "# Tauri Commands"
  echo ""
  echo "_Generated by \`./scripts/generate-api-docs.sh\`._"
  echo ""
  echo "This list is extracted from \`src-tauri/src/**\` by scanning for \`#[tauri::command]\`."
  echo ""

  # Print "command | file" rows.
  echo "| Command | Source |"
  echo "|--------:|:-------|"
  awk '
    /#\[tauri::command\]/ { in_cmd=1; next }
    in_cmd {
      if (match($0, /pub[[:space:]]+(async[[:space:]]+)?fn[[:space:]]+([A-Za-z0-9_]+)/, m)) {
        cmd=m[2]
        file=FILENAME
        sub(/^\.\//, "", file)
        print cmd "\t" file
        in_cmd=0
      }
    }
  ' $(find src-tauri/src -type f -name '*.rs' | sort) \
  | sort -u \
  | awk -F'\t' '{ printf("| `%s` | `%s` |\n", $1, $2) }'

  echo ""
  echo "See also: \`docs/API.md\`."
} > "$OUT_FILE"

echo "✅ Done"
